# Generated by Django 5.0.6 on 2024-05-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siteurso", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("valor", models.FloatField()),
            ],
        ),
    ]
